//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladiatorBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam_List()
        {
            this.c_cplus_Sets = new HashSet<c_cplus_Sets>();
            this.Csharp_Dotnet_Sets = new HashSet<Csharp_Dotnet_Sets>();
            this.Reports = new HashSet<Report>();
            this.Java_Sets = new HashSet<Java_Sets>();
            this.Sql_Sets = new HashSet<Sql_Sets>();
            this.php_Sets = new HashSet<php_Sets>();
            this.Python_Sets = new HashSet<Python_Sets>();
        }
    
        public int exam_id { get; set; }
        public string exam_name { get; set; }
        public int exam_set_counts { get; set; }
        public int total_marks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_cplus_Sets> c_cplus_Sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Csharp_Dotnet_Sets> Csharp_Dotnet_Sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Java_Sets> Java_Sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sql_Sets> Sql_Sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<php_Sets> php_Sets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Python_Sets> Python_Sets { get; set; }
    }
}
