//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladiatorBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineExamEntities : DbContext
    {
        public OnlineExamEntities()
            : base("name=OnlineExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<c_cplus_Sets> c_cplus_Sets { get; set; }
        public virtual DbSet<Csharp_Dotnet_Sets> Csharp_Dotnet_Sets { get; set; }
        public virtual DbSet<Exam_List> Exam_List { get; set; }
        public virtual DbSet<Java_Sets> Java_Sets { get; set; }
        public virtual DbSet<php_Sets> php_Sets { get; set; }
        public virtual DbSet<Python_Sets> Python_Sets { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Sql_Sets> Sql_Sets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
