//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladiatorBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Python_Sets
    {
        public string table_name { get; set; }
        public Nullable<int> exam_id { get; set; }
    
        public virtual Exam_List Exam_List { get; set; }
    }
}
