//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladiatorBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public string exam_name { get; set; }
        public int level1_score { get; set; }
        public int level2_score { get; set; }
        public int level3_score { get; set; }
    
        public virtual Exam_List Exam_List { get; set; }
        public virtual User User { get; set; }
    }
}
